services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: animetta-mc
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "false"
      TYPE: "PAPER"
      VERSION: "1.21"
      MODRINTH_PROJECTS: "paper:spectatorplus:paper-1.2.1"
      DIFFICULTY: "normal"
      GAMEMODE: "survival"
      MOTD: "Animetta MC Bot Test Server"
      MAX_PLAYERS: "10"
      OPS: "AnimettaBot"
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "6"
      ALLOW_FLIGHT: "true"
      SPAWN_PROTECTION: "0"
      ENABLE_COMMAND_BLOCK: "true"
      MAX_TICK_TIME: "180000"
      MEMORY: "4G"
    volumes:
      - ./data:/data
