"""
自动环境配置模块
一键检测环境、生成配置、安装依赖
"""

import os
import sys
import platform
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from loguru import logger


class AutoConfig:
    """自动环境配置器"""

    def __init__(self):
        self.project_root = Path(__file__).parent.parent.parent.parent
        self.env_info = self._detect_all()
        self.issues = []
        self.warnings = []

    def _detect_all(self) -> dict:
        """检测所有环境信息"""
        return {
            "platform": self._detect_platform(),
            "python_version": platform.python_version(),
            "python_executable": sys.executable,
            "gpu_available": self._check_gpu(),
            "cuda_version": self._get_cuda_version(),
            "data_dir_exists": False,
            "models_exist": False,
        }

    def _detect_platform(self) -> str:
        """检测平台"""
        system = platform.system().lower()

        if system == "windows":
            # 检查是否是WSL（通过环境变量）
            if os.getenv("WSL_DISTRO_NAME") or os.getenv("WSLENV"):
                return "wsl"
            return "windows"
        elif system == "linux":
            # 检查WSL
            if Path("/proc/version").exists():
                try:
                    with open("/proc/version") as f:
                        if "microsoft" in f.read().lower():
                            return "wsl"
                except:
                    pass
            return "linux"
        elif system == "darwin":
            return "macos"

        return "unknown"

    def _check_gpu(self) -> bool:
        """检查GPU可用性"""
        try:
            import torch
            return torch.cuda.is_available()
        except ImportError:
            return False

    def _get_cuda_version(self) -> Optional[str]:
        """获取CUDA版本"""
        try:
            import torch
            if torch.cuda.is_available():
                return torch.version.cuda
        except:
            pass
        return None

    def get_data_dir(self) -> Path:
        """智能获取数据目录"""
        platform_name = self.env_info["platform"]

        # 1. 检查环境变量
        env_dir = os.getenv("ANIMA_DATA_DIR")
        if env_dir:
            return Path(env_dir)

        # 2. 根据平台选择默认位置
        if platform_name == "windows":
            # Windows: E:/anima_data 或 C:/Users/xxx/anima_data
            e_drive = Path("E:/anima_data")
            if e_drive.exists():
                return e_drive
            return Path.home() / "anima_data"

        elif platform_name == "wsl":
            # WSL: 优先用 /mnt/e（共享数据），其次用 ~/anima_data
            mnt_e = Path("/mnt/e/anima_data")
            if mnt_e.exists():
                return mnt_e
            return Path.home() / "anima_data"

        else:  # linux, macos
            return Path.home() / "anima_data"

    def check_dependencies(self) -> Tuple[bool, List[str]]:
        """检查依赖是否安装"""
        missing = []
        required_packages = [
            "fastapi",
            "pydantic",
            "loguru",
            "yaml",
            "socketio",
        ]

        for package in required_packages:
            try:
                __import__(package)
            except ImportError:
                missing.append(package)

        return len(missing) == 0, missing

    def generate_env_file(self, force: bool = False) -> Path:
        """生成 .env 文件"""
        env_file = self.project_root / ".env"

        if env_file.exists() and not force:
            logger.info(f"✅ .env 文件已存在: {env_file}")
            return env_file

        data_dir = self.get_data_dir()
        platform_name = self.env_info["platform"]

        # 生成配置
        config = f"""# Auto-generated by Anima AutoConfig
# Platform: {platform_name.upper()}
# Generated: {__import__('datetime').datetime.now()}

# 数据目录
ANIMA_DATA_DIR={data_dir}

# 模型路径（自动配置）
ANIMA_BASE_MODEL_PATH={data_dir}/models/base_models/Qwen1.5-1.8B-Chat
ANIMA_LORA_PATH={data_dir}/models/checkpoints/neuro-vtuber-v1

# 向量数据库
ANIMA_VECTOR_DB_PATH={data_dir}/vectordb

# 对话历史
ANIMA_HISTORY_PATH={data_dir}/histories

# GLM API Key（如果使用GLM服务）
# GLM_API_KEY=your_key_here
"""

        env_file.write_text(config)
        logger.info(f"✅ 已生成 .env 文件: {env_file}")

        return env_file

    def generate_local_lora_config(self) -> Path:
        """生成 local_lora.yaml 配置"""
        config_file = self.project_root / "config" / "services" / "llm" / "local_lora.yaml"

        config_content = """# 本地 LoRA 微调模型配置（自动生成）
llm_config:
  type: local_lora
  base_model_name: "${ANIMA_BASE_MODEL_PATH}"
  lora_path: "${ANIMA_LORA_PATH}"
  device: cuda  # 会自动降级到 CPU
  max_new_tokens: 512
  temperature: 0.8
  top_p: 0.9
"""

        # 备份原配置
        if config_file.exists():
            backup = config_file.with_suffix(".yaml.bak")
            config_file.replace(backup)
            logger.info(f"📦 已备份原配置: {backup}")

        config_file.write_text(config_content)
        logger.info(f"✅ 已生成配置: {config_file}")

        return config_file

    def setup_data_dir(self) -> Path:
        """创建数据目录结构"""
        data_dir = self.get_data_dir()

        # 创建目录结构
        dirs = [
            data_dir,
            data_dir / "models" / "base_models",
            data_dir / "models" / "checkpoints",
            data_dir / "vectordb",
            data_dir / "histories",
        ]

        for dir_path in dirs:
            dir_path.mkdir(parents=True, exist_ok=True)

        logger.info(f"✅ 已创建数据目录: {data_dir}")

        return data_dir

    def auto_install_dependencies(self) -> bool:
        """自动安装依赖"""
        success = True

        try:
            logger.info("📦 检查依赖...")

            # 检查基础依赖
            all_ok, missing = self.check_dependencies()

            if all_ok:
                logger.info("✅ 所有依赖已安装")
                return True

            logger.warning(f"⚠️  缺少依赖: {', '.join(missing)}")
            logger.info("📦 正在安装...")

            # 安装依赖
            subprocess.check_call([
                sys.executable, "-m", "pip", "install",
                "-r", str(self.project_root / "requirements.txt"),
                "--quiet"
            ])

            logger.info("✅ 依赖安装完成")

        except subprocess.CalledProcessError as e:
            logger.error(f"❌ 依赖安装失败: {e}")
            success = False
        except Exception as e:
            logger.error(f"❌ 错误: {e}")
            success = False

        return success

    def diagnose(self) -> bool:
        """诊断环境，返回是否ready"""
        logger.info("=" * 60)
        logger.info("  Anima 环境诊断")
        logger.info("=" * 60)

        all_ok = True

        # 1. 平台信息
        logger.info(f"📌 平台: {self.env_info['platform'].upper()}")
        logger.info(f"🐍 Python: {self.env_info['python_version']}")
        logger.info("")

        # 2. GPU检测
        if self.env_info['gpu_available']:
            logger.info(f"✅ GPU: 可用 (CUDA {self.env_info['cuda_version']})")
        else:
            logger.warning("⚠️  GPU: 不可用（将使用CPU，速度较慢）")
            all_ok = False
        logger.info("")

        # 3. 数据目录
        data_dir = self.get_data_dir()
        if data_dir.exists():
            logger.info(f"✅ 数据目录: {data_dir}")
        else:
            logger.warning(f"⚠️  数据目录不存在: {data_dir}")
            all_ok = False
        logger.info("")

        # 4. 依赖检查
        deps_ok, missing = self.check_dependencies()
        if deps_ok:
            logger.info("✅ Python依赖: 完整")
        else:
            logger.warning(f"⚠️  Python依赖: 缺少 {', '.join(missing)}")
            all_ok = False
        logger.info("")

        # 5. 配置文件
        env_file = self.project_root / ".env"
        if env_file.exists():
            logger.info(f"✅ 配置文件: {env_file}")
        else:
            logger.warning(f"⚠️  配置文件不存在: {env_file}")
            all_ok = False
        logger.info("")

        logger.info("=" * 60)

        return all_ok

    def setup_all(self, auto_fix: bool = True) -> bool:
        """一键设置所有环境"""
        logger.info("🚀 开始自动配置...")

        success = True

        # 1. 生成 .env
        try:
            self.generate_env_file(force=False)
        except Exception as e:
            logger.error(f"❌ 生成 .env 失败: {e}")
            success = False

        # 2. 生成配置文件
        try:
            self.generate_local_lora_config()
        except Exception as e:
            logger.error(f"❌ 生成配置失败: {e}")
            success = False

        # 3. 创建数据目录
        try:
            self.setup_data_dir()
        except Exception as e:
            logger.error(f"❌ 创建目录失败: {e}")
            success = False

        # 4. 安装依赖
        if auto_fix:
            if not self.auto_install_dependencies():
                success = False

        return success


def main():
    """命令行入口"""
    import argparse

    parser = argparse.ArgumentParser(description="Anima 自动环境配置")
    parser.add_argument("--check", action="store_true", help="检查环境")
    parser.add_argument("--setup", action="store_true", help="自动配置环境")
    parser.add_argument("--force", action="store_true", help="强制覆盖配置")

    args = parser.parse_args()

    auto_config = AutoConfig()

    if args.check:
        ready = auto_config.diagnose()
        sys.exit(0 if ready else 1)

    elif args.setup:
        success = auto_config.setup_all(auto_fix=True)
        if success:
            logger.info("")
            logger.info("✅ 环境配置完成！")
            logger.info("")
            logger.info("下一步: python -m anima.socketio_server")
        sys.exit(0 if success else 1)

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
