"""Report rendering and persistence helpers for tech-tree runs."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from loguru import logger

from .models import TechTreeReport

_REPORT_DIR = Path("data") / "tech_tree_reports"


def render_markdown_report(report: TechTreeReport) -> str:
    """Generate a markdown summary of a tech tree run."""
    lines: list[str] = []
    lines.append("# Tech Tree Run Report\n")
    lines.append(f"**Generated:** {report.timestamp}\n")
    lines.append("## Summary\n")
    total_phases = len(report.core.config.phases)
    completed_phases = len(report.metrics.phases_completed)
    lines.append(f"- **Phases completed:** {completed_phases}/{total_phases}")
    lines.append(
        f"- **Total time:** {report.metrics.total_time_seconds:.1f}s "
        f"(budget: {report.core.config.total_time_budget_minutes}min)"
    )
    lines.append(f"- **Items collected:** {len(report.metrics.items_collected)} unique types")
    lines.append(f"- **Skills learned:** {report.metrics.skills_learned}")
    lines.append(f"- **Skills reused:** {report.metrics.skills_reused}")
    lines.append(f"- **Deaths:** {report.metrics.deaths}")
    completion_pct = report.metrics.completion_rate * 100
    status_icon = "✅" if completed_phases == total_phases else "⚠️"
    lines.append(f"- **Completion rate:** {status_icon} {completion_pct:.0f}%\n")
    lines.append("## Phase Details\n")
    for detail in report.phase_details:
        phase_name = detail.get("name", "unknown")
        completed = detail.get("completed", False)
        elapsed = detail.get("elapsed_seconds", 0.0)
        icon = "✅" if completed else "❌"
        lines.append(f"### {icon} {phase_name.title()} Phase\n")
        lines.append(f"- **Time spent:** {elapsed:.1f}s")
        items = detail.get("items_collected", {})
        if items:
            items_str = ", ".join(
                f"{item}×{count}" for item, count in sorted(items.items()) if count > 0
            )
            lines.append(f"- **Items:** {items_str}")
        missing = detail.get("missing_items", {})
        if missing:
            missing_str = ", ".join(
                f"{item} (need {count})" for item, count in sorted(missing.items())
            )
            lines.append(f"- **Missing:** {missing_str}")
        lines.append("")
    lines.append("## Final Inventory\n")
    if report.metrics.items_collected:
        for item, count in sorted(report.metrics.items_collected.items()):
            if count > 0:
                lines.append(f"- {item}: {count}")
    else:
        lines.append("*No items collected.*")
    lines.append("")
    lines.append("---\n*Report generated by TechTreeRunner*")
    return "\n".join(lines)


def save_markdown_report(
    report: TechTreeReport,
    markdown: str,
    directory: Path | str | None = None,
) -> Path:
    """Save a tech tree markdown report and return the file path."""
    target_dir = Path(directory) if directory else _REPORT_DIR
    target_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.fromisoformat(report.timestamp)
    filepath = target_dir / (ts.strftime("%Y-%m-%d_%H%M%S") + ".md")
    filepath.write_text(markdown, encoding="utf-8")
    logger.info(f"[TechTreeRunner] Report saved to {filepath}")
    return filepath
